version: '3'

services:
    # Frontend
    web:
        image: jitsi/web:stable-6865
        restart: ${RESTART_POLICY}
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        volumes:
            - ${CONFIG}/web:/config:Z
            # Images
            - ${CUSTOMFILES}/images/custom:/usr/share/jitsi-meet/images/custom
            # HTML Files
            - ${CUSTOMFILES}/html/body.html:/usr/share/jitsi-meet/body.html
            # Static files
            - ${CUSTOMFILES}/static/authError.html:/usr/share/jitsi-meet/static/authError.html
            - ${CUSTOMFILES}/static/close2.html:/usr/share/jitsi-meet/static/close2.html
            - ${CUSTOMFILES}/static/close2.html:/usr/share/jitsi-meet/static/close3.html
            - ${CUSTOMFILES}/static/js:/usr/share/jitsi-meet/static/js
            # Custom Branding
            - ${CUSTOMFILES}/html/dynamicBranding.json:/usr/share/jitsi-meet/dynamicBranding.json
            # Custom CSS
            - ${CUSTOMFILES}/css/styles.css:/usr/share/jitsi-meet/css/styles.css
            - ${CUSTOMFILES}/css/styles.css.map:/usr/share/jitsi-meet/css/styles.css.map
        environment:
            - AMPLITUDE_ID
            - ANALYTICS_SCRIPT_URLS
            - ANALYTICS_WHITELISTED_EVENTS
            - CALLSTATS_CUSTOM_SCRIPT_URL
            - CALLSTATS_ID
            - CALLSTATS_SECRET
            - CHROME_EXTENSION_BANNER_JSON
            - CONFCODE_URL
            - CONFIG_EXTERNAL_CONNECT
            - DEFAULT_LANGUAGE
            - DEPLOYMENTINFO_ENVIRONMENT
            - DEPLOYMENTINFO_ENVIRONMENT_TYPE
            - DEPLOYMENTINFO_REGION
            - DEPLOYMENTINFO_SHARD
            - DEPLOYMENTINFO_USERREGION
            - DESKTOP_SHARING_FRAMERATE_MAX
            - DESKTOP_SHARING_FRAMERATE_MIN
            - DIALIN_NUMBERS_URL
            - DIALOUT_AUTH_URL
            - DIALOUT_CODES_URL
            - DISABLE_AUDIO_LEVELS
            - DISABLE_DEEP_LINKING
            - DISABLE_HTTPS
            - DISABLE_POLLS
            - DISABLE_REACTIONS
            - DROPBOX_APPKEY
            - DROPBOX_REDIRECT_URI
            - DYNAMIC_BRANDING_URL
            - ENABLE_AUDIO_PROCESSING
            - ENABLE_AUTH
            - ENABLE_BREAKOUT_ROOMS
            - ENABLE_CALENDAR
            - ENABLE_CLOSE_PAGE
            - ENABLE_COLIBRI_WEBSOCKET
            - ENABLE_FILE_RECORDING_SERVICE
            - ENABLE_FILE_RECORDING_SERVICE_SHARING
            - ENABLE_FLOC
            - ENABLE_GUESTS
            - ENABLE_HSTS
            - ENABLE_HTTP_REDIRECT
            - ENABLE_IPV6
            - ENABLE_LETSENCRYPT
            - ENABLE_LIPSYNC
            - ENABLE_NOISY_MIC_DETECTION
            - ENABLE_NO_AUDIO_DETECTION
            - ENABLE_P2P
            - ENABLE_PREJOIN_PAGE
            - ENABLE_RECORDING
            - ENABLE_REMB
            - ENABLE_REQUIRE_DISPLAY_NAME
            - ENABLE_SIMULCAST
            - ENABLE_STATS_ID
            - ENABLE_STEREO
            - ENABLE_SUBDOMAINS
            - ENABLE_TALK_WHILE_MUTED
            - ENABLE_TCC
            - ENABLE_TRANSCRIPTIONS
            - ENABLE_WELCOME_PAGE
            - ENABLE_XMPP_WEBSOCKET
            - ETHERPAD_PUBLIC_URL
            - ETHERPAD_URL_BASE
            - GOOGLE_ANALYTICS_ID
            - GOOGLE_API_APP_CLIENT_ID
            - INVITE_SERVICE_URL
            - JICOFO_AUTH_USER
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL
            - LETSENCRYPT_USE_STAGING
            - MATOMO_ENDPOINT
            - MATOMO_SITE_ID
            - MICROSOFT_API_APP_CLIENT_ID
            - NGINX_RESOLVER
            - NGINX_WORKER_CONNECTIONS
            - NGINX_WORKER_PROCESSES
            - P2P_PREFERRED_CODEC
            - PEOPLE_SEARCH_URL
            - PUBLIC_URL
            - RESOLUTION
            - RESOLUTION_MIN
            - RESOLUTION_WIDTH
            - RESOLUTION_WIDTH_MIN
            - START_AUDIO_MUTED
            - START_AUDIO_ONLY
            - START_BITRATE
            - START_SILENT
            - START_VIDEO_MUTED
            - START_WITH_AUDIO_MUTED
            - START_WITH_VIDEO_MUTED
            - TESTING_CAP_SCREENSHARE_BITRATE
            - TESTING_OCTO_PROBABILITY
            - TOKEN_AUTH_URL
            - TZ
            - VIDEOQUALITY_BITRATE_H264_HIGH
            - VIDEOQUALITY_BITRATE_H264_LOW
            - VIDEOQUALITY_BITRATE_H264_STANDARD
            - VIDEOQUALITY_BITRATE_VP8_HIGH
            - VIDEOQUALITY_BITRATE_VP8_LOW
            - VIDEOQUALITY_BITRATE_VP8_STANDARD
            - VIDEOQUALITY_BITRATE_VP9_HIGH
            - VIDEOQUALITY_BITRATE_VP9_LOW
            - VIDEOQUALITY_BITRATE_VP9_STANDARD
            - VIDEOQUALITY_ENFORCE_PREFERRED_CODEC
            - VIDEOQUALITY_PREFERRED_CODEC
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE
            - XMPP_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
        networks:
            meet.jitsi:
                aliases:
                    - ${XMPP_DOMAIN}

    # XMPP server
    prosody:
        image: jitsi/prosody:stable-6865
        restart: ${RESTART_POLICY}
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody/config:/config:Z
            - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
            - ${CONFIG}/prosody/prosody-plugins-custom/mod_muc_lobby_rooms.lua:/prosody-plugins/mod_muc_lobby_rooms.lua:Z
        environment:
            - AUTH_TYPE
            - DISABLE_POLLS
            - ENABLE_AUTH
            - ENABLE_AV_MODERATION
            - ENABLE_BREAKOUT_ROOMS
            - ENABLE_GUESTS
            - ENABLE_LOBBY
            - ENABLE_XMPP_WEBSOCKET
            - GLOBAL_CONFIG
            - GLOBAL_MODULES
            - JIBRI_RECORDER_PASSWORD
            - JIBRI_RECORDER_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_XMPP_USER
            - JICOFO_AUTH_PASSWORD
            - JICOFO_AUTH_USER
            - JICOFO_COMPONENT_SECRET
            - JIGASI_XMPP_PASSWORD
            - JIGASI_XMPP_USER
            - JVB_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JWT_ACCEPTED_AUDIENCES
            - JWT_ACCEPTED_ISSUERS
            - JWT_ALLOW_EMPTY
            - JWT_APP_ID
            - JWT_APP_SECRET
            - JWT_ASAP_KEYSERVER
            - JWT_AUTH_TYPE
            - JWT_TOKEN_AUTH_MODULE
            - LDAP_AUTH_METHOD
            - LDAP_BASE
            - LDAP_BINDDN
            - LDAP_BINDPW
            - LDAP_FILTER
            - LDAP_START_TLS
            - LDAP_TLS_CACERT_DIR
            - LDAP_TLS_CACERT_FILE
            - LDAP_TLS_CHECK_PEER
            - LDAP_TLS_CIPHERS
            - LDAP_URL
            - LDAP_USE_TLS
            - LDAP_VERSION
            - LOG_LEVEL
            - PUBLIC_URL
            - TURNS_HOST
            - TURNS_PORT
            - TURN_CREDENTIALS
            - TURN_HOST
            - TURN_PORT
            - TZ
            - XMPP_AUTH_DOMAIN
            - XMPP_CROSS_DOMAIN
            - XMPP_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_MODULES
            - XMPP_MODULES
            - XMPP_MUC_DOMAIN
            - XMPP_MUC_MODULES
            - XMPP_RECORDER_DOMAIN
        networks:
            meet.jitsi:
                aliases:
                    - ${XMPP_SERVER}

    # Focus component
    jicofo:
        image: jitsi/jicofo:stable-6865
        restart: ${RESTART_POLICY}
        volumes:
            - ${CONFIG}/jicofo:/config:Z
        environment:
            - AUTH_TYPE
            - BRIDGE_AVG_PARTICIPANT_STRESS
            - BRIDGE_STRESS_THRESHOLD
            - ENABLE_AUTH
            - ENABLE_AUTO_LOGIN
            - ENABLE_AUTO_OWNER
            - ENABLE_CODEC_H264
            - ENABLE_CODEC_VP8
            - ENABLE_CODEC_VP9
            - ENABLE_OCTO
            - ENABLE_RECORDING
            - ENABLE_SCTP
            - JIBRI_BREWERY_MUC
            - JIBRI_PENDING_TIMEOUT
            - JIBRI_REQUEST_RETRIES
            - JICOFO_AUTH_PASSWORD
            - JICOFO_AUTH_USER
            #- JICOFO_COMPONENT_SECRET
            - JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT
            - JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT
            - JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS
            - JICOFO_ENABLE_HEALTH_CHECKS
            - JICOFO_RESERVATION_ENABLED
            - JICOFO_RESERVATION_REST_BASE_URL
            - JICOFO_SHORT_ID
            - JIGASI_BREWERY_MUC
            - JIGASI_SIP_URI
            - JVB_BREWERY_MUC
            - MAX_BRIDGE_PARTICIPANTS
            - OCTO_BRIDGE_SELECTION_STRATEGY
            - SENTRY_DSN="${JICOFO_SENTRY_DSN:-0}"
            - SENTRY_ENVIRONMENT
            - SENTRY_RELEASE
            - TZ
            - XMPP_AUTH_DOMAIN
            - XMPP_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_SERVER
        depends_on:
            - prosody
        networks:
            meet.jitsi:

    # Video bridge
    jvb:
        image: jitsi/jvb:stable-6865
        restart: ${RESTART_POLICY}
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
        volumes:
            - ${CONFIG}/jvb:/config:Z
        environment:
            - COLIBRI_REST_ENABLED
            - DOCKER_HOST_ADDRESS
            - ENABLE_COLIBRI_WEBSOCKET
            - ENABLE_OCTO
            - JVB_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_BREWERY_MUC
            #- JVB_ENABLE_APIS
            - JVB_OCTO_BIND_ADDRESS
            - JVB_OCTO_BIND_PORT
            - JVB_OCTO_PUBLIC_ADDRESS
            - JVB_OCTO_REGION
            - JVB_PORT
            - JVB_STUN_SERVERS
            - JVB_TCP_HARVESTER_DISABLED
            - JVB_TCP_MAPPED_PORT
            - JVB_TCP_PORT
            - JVB_WS_DOMAIN
            - JVB_WS_SERVER_ID
            - PUBLIC_URL
            - SENTRY_DSN="${JVB_SENTRY_DSN:-0}"
            - SENTRY_ENVIRONMENT
            - SENTRY_RELEASE
            - SHUTDOWN_REST_ENABLED
            - TZ
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
        depends_on:
            - prosody
        networks:
            meet.jitsi:
                aliases:
                    - jvb.meet.jitsi

# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
